### ISSUE TITLE
Partial score for test cases?

### ISSUE THREAD

**Issue by ongzexuan** [gradescope/autograder_samples#15]
I have a relatively common use case where I have a test case worth a total of X number of points, and the score can be anything between 0 and X inclusive. I don't see an example or mechanism where a partial score for a test case can be given. Is there a means to achieve this peacefully without some hack?

Currently I am thinking of just creating X test cases worth a single point each, running the actual test in the SetUp, and then having N test cases succeed where N is the student score obtained in the SetUp. I... can accept this, but this screws up the output for the students (students will then see X test cases).

**Comment by initmaks** [comment]
Is this what you are looking for https://github.com/gradescope/gradescope-utils/blob/master/gradescope_utils/autograder_utils/decorators.py#L87 ?

**Comment by ibrahima** [comment]
Hi @ongzexuan, thanks for your request! As initmaks mentioned, we do have a `partial_credit` decorator in our Python package.

However, I'm curious as to how your test with partial credit is set up. I imagine you have to assert multiple things along the way to figure out how much credit to assign, right? I think in some cases it can make sense to make N test cases where each asserts a different step along the path to the correct answer.

Hope that helps!
