### ISSUE TITLE
Dead internal link 

### ISSUE THREAD

**Issue by espertus** [gradescope/autograder_samples#88]
**Describe the bug**

On [java/README.md](https://github.com/gradescope/autograder_samples/tree/master/java#readme), the link with anchor text "Community Resources page" is dead. I get the same error at [https://gradescope-autograders.readthedocs.io/en/latest/java/](https://gradescope-autograders.readthedocs.io/en/latest/java/).

**To Reproduce**
Go to the page and click on "Community Resources page".

**Expected behavior**
I expected to go to another page. Instead, I got a 404 error.

**Comment by ibrahima** [comment]
Thanks for your PR, this is now fixed!
